# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WatermarkPdfTool.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon("logoMain.png"))
        MainWindow.setEnabled(True)
        MainWindow.resize(604, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(604, 450))
        MainWindow.setMaximumSize(QtCore.QSize(604, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(180, 10, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color: blue;")
        self.title.setObjectName("title")
        self.inputList = QtWidgets.QTextBrowser(self.centralwidget)
        self.inputList.setGeometry(QtCore.QRect(20, 70, 241, 192))
        self.inputList.setObjectName("inputList")
        self.outputList = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputList.setGeometry(QtCore.QRect(345, 70, 241, 311))
        self.outputList.setObjectName("outputList")
        self.btnSelectPdf = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectPdf.setGeometry(QtCore.QRect(270, 70, 61, 23))
        self.btnSelectPdf.setObjectName("btnSelectPdf")
        self.selectSave = QtWidgets.QPushButton(self.centralwidget)
        self.selectSave.setGeometry(QtCore.QRect(20, 310, 81, 23))
        self.selectSave.setObjectName("selectSave")
        self.lbSave = QtWidgets.QLabel(self.centralwidget)
        self.lbSave.setGeometry(QtCore.QRect(110, 310, 131, 16))
        self.lbSave.setObjectName("lbSave")
        self.inputPage = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPage.setGeometry(QtCore.QRect(20, 360, 251, 20))
        self.inputPage.setObjectName("inputPage")
        self.lb_listPage = QtWidgets.QLabel(self.centralwidget)
        self.lb_listPage.setGeometry(QtCore.QRect(20, 340, 251, 16))
        self.lb_listPage.setObjectName("lb_listPage")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(330, 390, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.btnClearInput = QtWidgets.QPushButton(self.centralwidget)
        self.btnClearInput.setGeometry(QtCore.QRect(270, 130, 61, 23))
        self.btnClearInput.setObjectName("btnClearInput")
        self.btnNewWatermark = QtWidgets.QPushButton(self.centralwidget)
        self.btnNewWatermark.setGeometry(QtCore.QRect(190, 270, 71, 23))
        self.btnNewWatermark.setObjectName("btnNewWatermark")
        self.btnSelectFolder = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectFolder.setGeometry(QtCore.QRect(270, 100, 61, 23))
        self.btnSelectFolder.setObjectName("btnSelectFolder")
        self.listPdfWatermark = QtWidgets.QComboBox(self.centralwidget)
        self.listPdfWatermark.setGeometry(QtCore.QRect(20, 270, 131, 22))
        self.listPdfWatermark.setObjectName("listPdfWatermark")
        self.btnDelWatermark = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelWatermark.setGeometry(QtCore.QRect(160, 270, 31, 23))
        self.btnDelWatermark.setObjectName("btnDelWatermark")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(270, 160, 61, 51))
        self.btnStart.setObjectName("btnStart")
        self.btnResetPath = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetPath.setGeometry(QtCore.QRect(245, 310, 20, 23))
        self.btnResetPath.setObjectName("btnResetPath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Đóng dấu PDF"))
        self.title.setText(_translate("MainWindow", "TOOL ĐÓNG DẤU PDF"))
        self.btnSelectPdf.setText(_translate("MainWindow", "Chọn PDF"))
        self.selectSave.setText(_translate("MainWindow", "Lưu trữ"))
        self.lbSave.setText(_translate("MainWindow", "/"))
        self.lb_listPage.setText(_translate("MainWindow", "Đóng dấu các trang (Để trống để đánh dấu tất cả)"))
        self.info.setText(_translate("MainWindow", "Dev: Nguyen Huy Tuong | facebook.com/huytuong010101"))
        self.btnClearInput.setText(_translate("MainWindow", "Xóa tất cả"))
        self.btnNewWatermark.setText(_translate("MainWindow", "Tạo mới"))
        self.btnSelectFolder.setText(_translate("MainWindow", "Thư mục"))
        self.btnDelWatermark.setText(_translate("MainWindow", "Xóa"))
        self.btnStart.setText(_translate("MainWindow", "Chuyển"))
        self.btnResetPath.setText(_translate("MainWindow", "X"))



